---
- name: Check for OS updates and fail if any are available
  hosts: all
  become: false
  gather_facts: yes

  tasks:
    - name: Check for package updates on Debian/Ubuntu (via sudo apt)
      ansible.builtin.shell: |
        set -e
        # Refresh package lists
        sudo apt update -y > /dev/null 2>&1

        # List upgradable packages, skip the "Listing..." header line
        sudo apt list --upgradable 2>/dev/null \
          | awk -F/ 'NR>1 {print $1}'
      register: apt_result
      changed_when: apt_result.stdout != ""
      failed_when: apt_result.rc != 0
      check_mode: no        # still run even with --check
      when: ansible_os_family == "Debian"

    - name: Fail if updates are available on Debian/Ubuntu
      ansible.builtin.fail:
        msg: >
          There are pending package updates on this host
          (Debian/Ubuntu). Please update before continuing.
      when:
        - ansible_os_family == "Debian"
        - apt_result.stdout != ""

    - name: Check for package updates on RHEL/Rocky (via sudo dnf check-update)
      ansible.builtin.shell: |
        sudo dnf -q check-update
      register: dnf_result
      # dnf check-update returns:
      #  0   = no updates
      #  100 = updates available
      # >100 = error
      failed_when: dnf_result.rc not in [0, 100]
      changed_when: dnf_result.rc == 100
      check_mode: no
      when: ansible_os_family == "RedHat"

    - name: Fail if updates are available on RHEL/Rocky
      ansible.builtin.fail:
        msg: >
          There are pending package updates on this host
          (RHEL/Rocky). Please update before continuing.
      when:
        - ansible_os_family == "RedHat"
        - dnf_result.rc == 100
